# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 20:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ama',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='ama',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 20, 50, 27, 166212, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='answer',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 20, 50, 27, 167383, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 9, 20, 50, 27, 166771, tzinfo=utc)),
        ),
    ]
