# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 18:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20160609_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author_name',
            field=models.CharField(default=b'Anonymous', max_length=25),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
