# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-08 19:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20160617_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ama',
            old_name='description_text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='answer_text',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
